# Файл docker-compose должен начинаться с тега версии.
# Мы используем "3" так как это - самая свежая версия на момент написания этого кода.

version: '3'

# Следует учитывать, что docker-composes работает с сервисами.
# 1 сервис = 1 контейнер.
# Сервисом может быть клиент, сервер, сервер баз данных...
# Раздел, в котором будут описаны сервисы, начинается с 'services'.

services:
  # Сервис для поднятия СУБД Mysql
  db:
    # Ключевое слово "build" позволяет задать
    # путь к файлу Dockerfile, который нужно использовать для создания образа,
    # который позволит запустить сервис.

    build: db/

    ports:
      - '3306:3306'
    tty: true
    command: echo "test"

  # Сервис для собственно сайта

  server:
    build: server/

    # Пробросим порт 80 на 3000 порт коспьютера

    ports:
      - '80:80'
    tty: true
    command: echo "test"
  # Ключевое слово 'depends_on' позволяет указывать, должен ли сервис,
  # прежде чем запуститься, ждать, когда будут готовы к работе другие сервисы.
  # Нам нужно, чтобы сервис 'client' дождался бы готовности к работе сервиса 'server'.
