version: '3'

services:
  # Service for DBMS MYSQL
  db:
    image: mysql
    # Mysql port 3306
    ports:
      - '3306:3306'
    #
    volumes:
      - ./db:/var/lib/mysql
    environment:
      # MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: SashaSasha100
      # MYSQL_DATABASE: mineral
      # MYSQL_USER: user
      # MYSQL_PASSWORD: password

  # Service for apache2 web server
  server:
    build: server/
    volumes:
      - ./server:/var/www/html
    # Web server port 80
    ports:
      - '80:80'
    tty: true
